export const projects = [
  {
    title: 'RGB Game',
    description: "Game to determine right shade of colour for a given values of RGB. it is a single page website which will has a beautiful UI. a random RGB shade is given to the user with the help of which user needs to find out the correct correspdonding color.",
      image: '/images/11.png',
      tags: ['HTML', 'CSS', 'JAVASCRIPT'],
    source: 'https://fayaz-ui.github.io/rgb_game/',
    visit: 'https://github.com/fayaz-ui/rgb_game',
    id: 0,
  },
  {
    title: 'Currency Converter',
    description:"This is an API Based simple website which shows the real time currency value from the different region of the world. it is created using Frankfurter API, Frankfurter is an open-source API for current and historical foreign exchange rates published by the European Central Bank.",
    image: '/images/12.png',
    tags: ['HTML', 'CSS','JavaScript'],
    source: 'https://fayaz-ui.github.io/CURRENCY_CONVERTER/',
    visit: 'https://github.com/fayaz-ui/CURRENCY_CONVERTER',
    id: 1,
  },
  {
    title: 'Sorting Visualizer',
    description: "This project is built using HTML, CSS, and JS. This project sorting visualizer is a very simple UI and it allows the users to select the sort algorithm, select the array size, and speed of the visualization",
      image: '/images/13.png',
      tags: ['HTML', 'CSS','JAVASCRIPT'],
    source: 'https://visualizesorting-app.netlify.app/',
    visit: 'https://github.com/fayaz-ui/algo-visualizer',
    id: 2,
  },
  {
    title: 'LinkTree Clone',
    description: "this is a website that provides you with a unique URL to list in your social media profile. When someone click on it, they will be led to your linktree site with multiple links available for them to click on! ",
    image: '/images/14.png',
    tags: ['HTML', 'CSS', 'JAVASCRIPT'],
    source: 'https://fayaz-ui.github.io/my_all_links/',
    visit: 'https://github.com/fayaz-ui/my_all_links',
    id: 3,
  },
  {
    title: 'Tic-Tac-Toe Game',
    description: "Tic-tac-toe is a two player game (one of them being your computer program). The two players take turns putting marks on a 3x3 board. The player who first gets 3 of his/her marks in a row (vertically, horizontally, or diagonally) wins the game, and the other loses the game.",
    image: '/images/15.png',
    tags: ['REACT.JS', 'CSS', 'HTML'],
    source: 'https://javascript-react-tic-tac-toe.netlify.app/',
    visit: 'https://github.com/fayaz-ui/tic-tac-toe',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey from AMU after high school', },
  { year: 2018, text: 'Explored Embedded sysytem and Electronics', },
  { year: 2019, text: 'Started exploring core concepts in ECE and EE', },
  { year: 2020, text: 'Started exploring CS/IT Domain', },
  { year: 2021, text: 'Completed few projects in Web Development', },
  { year: 2022, text: 'Learning DSA and Core Concepts of Software Industry', },
];